name: smoke_test

on:
  pull_request:
    branches:
      - master
      - release-*
jobs:
  smoke_test:
    name: Run smoke_test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run smoke_test
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          cd scripts
          echo ${{ github.base_ref }}
          bash smoke_test.sh -b ${{ github.base_ref }}



